In [2]:
import numpy as np
import pandas as pd
import os
import math

In [55]:
# string 변수 만들기
# name.capitalize()
name='dongsoo'

name.capitalize()
name.count('o') # name 에 'o'라는 문자가 몇개 있는지 카운팅

name.split('o') # name에 'o'라는 문자를 제거후 출력

name_split=name.split('g')
type(name_split)

name_split[0] # name 이라는 리스트에서 'g'문자를 제거후 첫번째 리스트(don) 을 출력

text='I\'m Jongho'
text

s1='Python'
s1=s1+'Python'
s1

In [66]:
# 변수 지우기 'del 변수명'
# 사용한 변수명 확인하기 'dir()'
a,b = 10, 20
print(a,b)

v1, v2, v3 = 10, 20, 30
print(v1,v2,v3)

10 20
10 20 30


In [ ]:
# Containers : '자료를 담는 통' -> list[], tuple(), set{}, frozenset{}, dictionary{}

# list[] : 리스트 이름을 변경 가능하고 수정 가능함 옮기는것도 가능
# tuple() : 자료의 변경을 허용하지 않는 구조
# set{} : 자료추가가 가능하며 겹치는 자료의 유무를 알아내는데 유용하다.
# frozenset{} : set를 한번 만들면 자료 변경과 추가가 불가능하다.
# dictionary{} : 방에 이름이 쓰여져 있고 방안에 자료가 들어간다. 해당 columns을 알아야 데이터를 찾을 수 있다.

In [70]:
# list[]

my_list1= [10, 10.1, 'python', True]
my_list1
type(my_list1)

my_list1 = list([1,2,3])
my_list1

[1, 2, 3]

In [73]:
# tuple()
my_tuple1=(10, 10.1, 'python', True)
my_tuple1
type(my_tuple1)

my_tuple1= tuple([1,2,3])
my_tuple1

(1, 2, 3)

In [77]:
# list 와 tuple 은 sequence 타입으로 불린다. sequence -> 순서적으로 되어있고 방에있는 자료를 불러올 수 있음

1

In [81]:
# 자료가 list타입일 경우 변경하는 방법

vip_names=['Newton', 'Euler', 'Gauss']
vip_names[0]='Kepler' # vip_namse의 첫번째에 있는 'Newton' 값을 'Kepler'로 변경
vip_names

# 자료가 tuple일 경우 변경하는 방법 (list와 같이 변경하면 오류가 발생)


['Kepler', 'Euler', 'Gauss']

In [86]:
my_list1=[10,20,30,40,50]
my_list1[:] # 모든 자료를 가져오고 싶을 때 ':'을 사용

my_list1[0:4:1] # 마지막 1은 증가량을 의미; 적지 않을 경우 자동으로 1로 인식

my_list1[-1] # '-1'은 끝에있는 값을 가져옴

my_list1[-1::-1] # 중간에 끝의 값을 적지 않고 건너 뛰면 자동으로 1단위로 인식

my_list1[-1:-6:-1]

[50, 40, 30, 20, 10]

In [102]:
#my_list2=[[10,20,30,40,50],[20]]
#my_list2

#my_list3=[[10,20,30],[40,50,60]]
#my_list3

my_list4=[[10,20,30],
          [40,50,60]]

my_list4
my_list4[1][0:2] # my_list4의 두번째 방에서 두번째 값까지만 출력

my_list5=[[10,20,[100,200,300]], [40,50,60]]
my_list5

print(my_list5[0][2][0])
print(my_list5[0][2][1])
print(my_list5[0][2][2])
print(my_list5[1][2]) 

100
200
300
60


In [107]:
#list 더하기
my_list1 = [10,20,30]
my_list2=[100,200,300]
my_list1+my_list2

my_list1=[[10,20],[30,40]]
my_list2=[[40,60],[70,80]]

my_list1+my_list2

my_list3= my_list1+my_list2
my_list3

[[10, 20], [30, 40]]

In [108]:
my_list1*2

[[10, 20], [30, 40], [10, 20], [30, 40]]

In [109]:
old_list=[10,20,30,40,50]
new_list=old_list

old_list[0]=100

print(new_list, old_list) # 위의 수식처럼 리스트를 변경하면 기존의 변수도 같이 변경이 된다.

[100, 20, 30, 40, 50] [100, 20, 30, 40, 50]


In [111]:
# list 더하기 -> extend
num_list1=[10,20,30]
num_list2=[40,50,60]
num_list1.extend(num_list2)
num_list1

num_list1=num_list1+num_list2
num_list1

[10, 20, 30, 40, 50, 60, 40, 50, 60]

In [127]:
# append : 변수추가

vip_names=['Newton','Euler','Gauss']
vip_names.append('Kepler') # append 함수를 이용하여 'Kepler'라는 변수 추가
vip_names

# pop : 변수 삭제
vip_names.pop(0)
vip_names

# insert : 변수추가
vip_names.insert(5,'Gauss')
vip_names

# index : 해당 변수가 몇번째 index 에 있는지 찾아줌
vip_names.index('Gauss')

# sort : 알파벳 순으로 정렬
vip_names.sort()
vip_names

# reverse : 반대로 정렬
vip_names
vip_names.reverse()
vip_names

data=[['Asia',24],
      ['America',25],
      ['Europe',20],
      ['Africa',28],
      ['Austrilia',23]]
data

[['Asia', 24],
 ['America', 25],
 ['Europe', 20],
 ['Africa', 28],
 ['Austrilia', 23]]

In [158]:
# Set type

my_set1={10,20,30}
my_set2={10, 'Jongho',True}
my_set3={10,20,30,20}
my_set3


my_list4=[10,20,30,40,50]
my_set4=set(my_list4)
my_set4

b=set()
b

my_set1.add(40)
my_set1
my_set1.update([30,50])
my_set1

A={10,20,30,40,50}
B={40,50,60,70,80}

A|B # A 와 B를 결합하여 출력

A.union(B) # A 와 B의 합집합

A&B # A와 B의 교집합
A.intersection(B)

A-B
A.difference(B) # A와 B의 차집합

A.symmetric_difference(B) # A와 B가 중복되지 않는 부분만을 출력

A.issubset(B) # A의 값들이 B에 다 들어가 있는지 확인해줌 Ture, False로 출력

# Frozenset
A=frozenset([10,20,30,40,50])
B=frozenset([40,50,60,70,80])
print(A,B)

#A.add(100) 'frozenset'는 추가되지 않는다

A=frozenset([10,20,30,40,50])
B=set([40,50,60,70,80])

A&B

vip_names=['Newton','Kepler','Euler','Galileo']
door1_list=['Newton']
door2_list=['Euler','Galileo']

door1_list in vip_names # door1_list에 리스트값[x]를 입력을 안했기 때문에 False 라고 뜬다.

door1_list[0] in vip_names

All=set(vip_names)
D1=set(door1_list)
D2=set(door2_list)

print(D1.issubset(All),D2.issubset(All))

D_combined=D1|D2
D_combined.issubset(All)

All-D_combined
Missing=All-D_combined
Missing

door1_list=['Newton','Jongho']
door2_list=['Euler','Jongho']
D1=set(door1_list)
D2=set(door2_list)
combined=D1|D2
combined.issubset(All)

frozenset({40, 10, 50, 20, 30}) frozenset({70, 40, 80, 50, 60})
True True


False

In [6]:
# Dictionary -> 키,값 형태

my_dict={'A':'Jongho', 'B':'Hojun', 'C':'Jaewook'}
my_dict['A']
my_dict={'C':'Jaewook','A':'Jongho','B':'Hojun'}
my_dict['C']

phone_book={'Jongho':'1111-1111',
            'Hojun':'222-2222',
            'Jaewook':'333-3333'}
phone_book['Jongho']

phone_book.get('Jongho')

phone_book['Jongho']='777-7777' # dict 값 변경
phone_book.get('Jongho')

phone_book.update({'Jongho':'999-9999'}) # 위와 마찬가지로 dict값 업데이트(변경)
phone_book

'Jongho' in phone_book

phone_book.pop('Hojun') # dict 의 키-값 제거
phone_book

my_list=[10,20,30,40,50]
my_tuple=(10,20,30,40,50)
my_set={10,20,30,40,50}

# print(len(my_list),len(my_tuple), len(my_set)) 함수의 길이 출력
# print(max(my_list),max(my_tuple), max(my_set)) 함수의 최댓값 출력
# print(min(my_list), min(my_tuple), min(my_set)) 함수의 최솟값 출력

member_list=['Kevin',24,'Python']
name=member_list[0]
age=member_list[1]
lan=member_list[2]

# print(name, age, lan)

# name, age, lan =member_list
# print(name, age, lan)

name, *pdata=member_list # * -> 뒤에 붙은 변수는 별도로 리스트화 해서 출력
#print(name, pdata)

num_list = [10,20,30,40,50]
first, *rest=num_list
#print(first, rest)

first, *body, last=num_list
print(first, body, last, pdata)

10 [20, 30, 40] 50 [24, 'Python']


In [12]:
# range : list함수를 만들때 유용함.

range(0,20,2)
r=range(0,20,2) # 0부터 20까지 2씩 증가

11 in r

r.index(10) # 10이 몇번째 index에 있는지 출력
r[:5]
r[-1]

list(range(10,50,10))
list(range(10,50,1))


 # for 문
for i in range(5):  # range에 들어가 있는 숫자를 출력
    print(i)

for i in range(2,10,2):
    print(i)

for i in range(10,2,-2):
    print(i)

0
1
2
3
4
2
4
6
8
10
8
6
4


In [37]:
# string(str)
s='Python'
s[0::2]
s[::3]
s='python'
s.capitalize()
s.find('t')
s='Python'
s.find('P')
s='PPython'
s.index('P')
s.isalpha() # s에 알파벳만 들어가 있는지 확인 True, Flase 출력

s='Python 3'
s.isalnum()

s='234'
s.isdecimal() # 0-9사이의 숫자만 있기때문에 True

s.isdigit() # isdecimal과 마찬가지

s='I like Python\nHe likes Python \nshe Likes Python' # \n 줄바꿈 문자
print(s)

t=s.splitlines() # splitlines : 라인별 문장을 리스트로 출력
type(t)

s='python'
s.upper()

s='pppppython'
s.count('p')

I like Python
He likes Python 
she Likes Python


5

Format & Print

In [56]:
s='Python'
v=3
print(s,v) # s, v 를 분리해서 출력
print(s+str(v)) # s,v 를 띄워쓰지 않고 출력
print(s + ' '+ str(v)) # ' '로 중간에 여백을 두고 출력

s='Python 3'
s='Python {}'
s.format(1+2) # 위의 { }안에 format 변환에 대한 값을 출력

s='Python {} {}' 
s.format(3, 'Released') 

s='Python {1} {0}'
s.format(3, 'Released') # 위의 중괄호 안의 인수로 인해 포맷변환의 순서 변경

data = 4312.1235663
print('data='+str(data))

print('DATA={:2f}'.format(data)) # 소숫점 2째 자리 까지 포맷
print('Data={:7.0f}'.format(data)) # {:x.yf} : x=출력을 원하는 자리, y=소숫점 위치
print('Data={:,}'.format(data)) # 숫자를 보기 편하게 ','로 표시
print('Data={:d}'.format(int(data))) # 정수부분만 출력
print('Data={:e}'.format(data))
print('Data=%(x)f'%{'x': data}) # x라는 키를 찾아서 data의 값을 넣어서 출력
print('Data=%(x).2f'%{'x':data}) # output : 4312.12

Python 3
Python3
Python 3
data=4312.1235663
DATA=4312.123566
Data=   4312
Data=4,312.1235663
Data=4312
Data=4.312124e+03
Data=4312.123566
Data=4312.12


Math Module

In [70]:
import math
math.floor(math.pi)
math.ceil(math.pi)

p=math.pi
p

math.sin(p/2)

x_degree=90
x_radian = x_degree*(p/180)
x_radian

math.sqrt(4)
math.pow(2,3)
2**3 # 2의 3승

x=2
math.isinf(x)
math.fsum([1,2,3]) # 리스트 안에 있는 숫자를 다 더해줌

6.0

OS Module

In [76]:
import os
os.getcwd() # 현재 디렉토리를 알려주는 함수

# os.chdir : 디렉토리를 변경해주는 함수
# os.chidr('..') : '..' 현재 있는 디렉토리에서 바로 상위 디렉토리로 이동
# os.rename('박종호','dir1') : '박종호'라는 이름의 디렉토리를 'dir1'으로 이름을 변경하는 함수
# os.remove('dir0', 'dir100') : 디렉토리를 제거

import sys
sys.modules # 현재 파이썬에서 쓰고 있는 모듈

sys.path # 나만의 모듈을 만들고 싶을때 path 에 등록을 하면 어디에서든 쓸 수 있다.

['c:\\Users\\LG\\Desktop\\박종호',
 'c:\\Users\\LG\\anaconda3\\python310.zip',
 'c:\\Users\\LG\\anaconda3\\DLLs',
 'c:\\Users\\LG\\anaconda3\\lib',
 'c:\\Users\\LG\\anaconda3',
 '',
 'c:\\Users\\LG\\anaconda3\\lib\\site-packages',
 'c:\\Users\\LG\\anaconda3\\lib\\site-packages\\win32',
 'c:\\Users\\LG\\anaconda3\\lib\\site-packages\\win32\\lib',
 'c:\\Users\\LG\\anaconda3\\lib\\site-packages\\Pythonwin']

Input Output

In [126]:
f=open('file1.txt','w') # 파일을 사용하고 싶을때 'w' '박종호'폴더에 file1 이라는 txt 파일 생성
type(f)
f.closed # 파일을 사용할 수 있는지 여부를 확인 True 일 경우 파일을 사용할 수 없음
f.write('I love dam')
f.close()
f.closed

with open('file2.txt','w') as f: # with를 사용하면 f.closed를 사용하여 파일을 닫지 않아도 알아서 닫힘
    f.write('I love dam\n')    
    f.write('I love lol')

f.closed

fid=open('file2.txt','r') # file2 라는 텍스트 파일 불러오기
#fid.read()
data=[] # list 형식의 data 생성
data.append(fid.readline(10)) # fid(file2)의 첫번째 줄을 list 형식의 data에 적용, readline() 안에 숫자를 입력하면 해당 문자열까지 리스트로 적용해서 출력
data

In [135]:
fid = open('file2.txt','r')
data=[]
data.append(fid.readline())
data.append(fid.readline())
data
for line in fid:
    line

['str1', 'str2', 'str3']

In [142]:
data=['str1','str2','str3']
data

import json
f=open('file3.txt','w')
json.dump(data,f) # data란 파일을 json형식으로 넣어 놓겠다는 의미
f.close()

f=open('file3.txt','r')
x=json.load(f)
type(x)
f.closed

False

In [153]:
import pickle
f=open('file4.txt','wb')
pickle.dump(data,f)
f.close()
f.closed

f=open('file4.txt','r')
#pickle.load(f)
f.close()
f.closed

True

In [161]:
f=open('file4.txt','rb') # 특수 텍스트가 들어가서 'rb'로 불러옴
x=pickle.load(f)
x
f.close()
f.closed

True

Scipy.org
1. Numpy
2. Sympy
3. Matplotlib
4. Scypy
5. Pandas

In [183]:
# Numpy 는 행렬 계산에 최적화된 함수
import numpy as np
a=np.arange(10) # 0부터 10까지 리스트로 출력
a 
a=np.array([10,20,30])
a

# size에 관련된 변수들
#a.shape # output이 3, 인것은 1차원([10,20,30]) 으로 구성되어 있기때문에 
#a.ndim # a가 몇차원으로 구성되어 있는지 출력
#a.dtype
#a.itemsize # a에 몇바이트 들어있는지 확인
#a.size # a array에 값이 몇개가 들어가 있는지 알려줌
#type(a)

a=np.array([10,20,30])
a.dtype

a[2]=30.1
a # 30.1 이 아니라 소숫점이 날라간 정수타입으로 출력

a.dtype.name
a=a.astype('float64') # 소숫점 단위도 출력 가능하게 변환
a[2]=30.1
a

b=np.array([10,20,30.])
b

c=np.array([10.1,20.1,30.1], 'int32')
c

array([10, 20, 30])

In [198]:
x=np.array([7,9,11])
y=x/2
x.dtype # 정수타입 int32
y.dtype # 실수타입 float64

a=np.array([[10,20,30],
           [40,50,60]])
a.shape

a=np.array(
    [
        [[10,50],[20,60]],
        [[30,70],[40,80]]
    ]
)
a

#a=np.array([10+10j, 20+20j])
#a
a=np.array([10,20],'complex')
a.dtype

dtype('complex128')

In [212]:
# numpy matrix
a=np.array([10,20]) # 1차원 행렬(2,)
b=np.matrix([10,20]) # 2차원 행렬(1,2)
print(a.shape,b.shape)

b=np.matrix([[10,20],[30,40]])
print(b, b.shape)

a=np.array([10,20,30])
a=np.insert(a,0,5) # insert(arr, obj, values, axis=None) -> insert(array, object, values, axis) /  a 변수에 0번째 index에 5를 삽입
a

a=np.linspace(0,5,6)
a

(2,) (1, 2)
[[10 20]
 [30 40]] (2, 2)


array([0., 1., 2., 3., 4., 5.])

In [228]:
a=np.array([10,20,30])
b=np.array([ 1, 2, 3])

c1=a+b
c2=a-b
c3=b**2
c4=2*a
print(c1,c2,c3,c4)

idx1=b<20
idx2=a<20
print(idx1, idx2)

a=np.array([10.,20.,30.])
b=np.array([1,2,3])

f1=np.add(a,b) # a+b
f2=np.subtract(a,b) # a-b
f3=np.multiply(a,b) # a*b
f4=np.divide(a,b) # a/b
f5=np.divmod(a,b) # 나머지 자리 찾아주는 함수 divmod
f6=np.exp(b)
f7=np.sqrt(b)

print(f1,f2,f3,f4,f5,f6,f7)

[11 22 33] [ 9 18 27] [1 4 9] [20 40 60]
[ True  True  True] [ True False False]
[11. 22. 33.] [ 9. 18. 27.] [10. 40. 90.] [10. 10. 10.] (array([10., 10., 10.]), array([0., 0., 0.])) [ 2.71828183  7.3890561  20.08553692] [1.         1.41421356 1.73205081]


In [233]:
# np.average(a) # a의 평균
# np.average(x,weights=[1,1,1]) # x의 평균인데 weights라는 가중치 부여
# np.median(a) # a의 중앙값
# np.cumsum(a) # a리스트속의 앞의 값을 더한 값 출력

15.0

In [255]:
#x=np.array([10,20,30])
#x.sum()

x=np.array([10.,20.,30.,25.,15.])
x.min() # x 의 최소값
x.argmin() # 최소값이 위치한 자리를 출력

x_min, x_min_idx=x.min(), x.argmin()

x.max()
x_max, x_max_idx=x.max(), x.argmax()

x.ptp() # 최소값과 최대값의 차이를 알려줌

x=np.array([10.,20.,30.,25.,15.])
y=np.sort(x) # x의 값을 순서대로 정렬
print(x,y)

idx=np.argsort(x) # sort 되기전의 위치값을 출력
idx

a=np.array([10,20,30])
b=np.array([-5,25])
np.searchsorted(a,b) # a에 insert를 하고 싶을때 어느 위치를 입력해야 하는지 알려줌

[10. 20. 30. 25. 15.] [10. 15. 20. 25. 30.]


array([1, 2, 3, 4, 5, 6])

In [312]:
d=np.arange(1,7,1)
d

e=d.reshape(2,3)
g=np.linspace(1,10,10).reshape(2,5)
g

a=np.array([[1,2],[3,4]])
a1=np.repeat(a,2, axis=0) # a 리스트를 2번 반복하고 밑의 방향으로 리스트를 출력
a2=np.repeat(a,2,axis=1) # a 리스트를 2번 반복하고 오른쪽의 방향으로 리스트를 출력
# print(a2)
np.repeat(a,[1,2],axis=0) # a 리스트의 첫번째에 있는 열은 한번 반복, 두번째에 있는 열은 두번 반복하라는 의미
np.repeat(a, [1,3],axis=0)

np.repeat(a,[1,2], axis=1)
np.repeat(a,[2,1],axis=1)

a=np.array([[1],[2],[3]])
b=np.array([[4],[5],[6]])
c=np.concatenate((a,b),axis=0) # a와 b 리스트를 밑으로 연결 # 단 튜플형태로 입력해야한다.
d=np.concatenate((a,b),axis=1) # a와 b 리스트를 오른쪽으로 연결
#print(c)
#print(d)

a=np.array([10,20,30])
b=np.array([40,50,60])
np.vstack((a,b)) # a,b를 행단위로 연결
np.hstack((a,b)) # a,b를 열단위로 연결

A=np.array([[10.,20.,30.],
            [40.,50.,60.]])

np.hsplit(A,3) # 행단위로 3개로 나눔
np.vsplit(A,2) # 열단위로 2개로 나눔

A=np.array([[10,20,30],[40,50,60]])
A.transpose() # 행열을 바꿔주는 함수
A.ravel() #2차원의 함수를 1차원으로 변경, 한줄 정렬
A.reshape(-1) # 한줄로 정렬
A.ravel(order='C')
A.ravel(order='F')

A=np.array([[1,2,3]]) # (1,3) 차원

B=A.squeeze() # squeeze 함수를 이용해 차원을 축소
B.shape

A=np.array([[[1,2]],
            [[3,4]],
            [[5,6]]])
A

B=A.squeeze()
B

array([[1, 2],
       [3, 4],
       [5, 6]])

## [1,2,3] 행렬과 [4,5,6] 행렬의 결합

In [323]:
A1=np.array([1,2,3])
B1=np.array([4,5,6])

A2=A1[:,np.newaxis] # A1의 모든 숫자들을 선택한 후 차원을 하나 더 추가해준다.
B2=B1[:,np.newaxis]
A2.shape # (3,1) 차원
A1.shape # (3,) 차원


np.concatenate((A2,B2),axis=0)
np.concatenate((A2,B2),axis=1)

np.vstack((A1,B1)).transpose()
np.hstack((A1,B1)).reshape(2,3).transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [332]:
# shallow copy
A=np.array([10,20,30,40])
B=A.view()

# deep copy
A=np.array([10,20,30,40])
B=A.copy()

False

## Logic Function

In [22]:
a=np.array([0,1,2])
a.all() # a라는 array에 모든 값이 참인지 True False 값으로 출력
a.any() # 하나라도 참이 있을경우 True 값을 출력
a.nonzero() # a 라는 array에 0을 제외한 값을 출력


a=np.array([0,10,20])
np.where(a>0) # a라는 array에 a>0 조건을 만족하는 값이 어디에 있는지 알려주는 함수

a=np.array([10,0,20])
np.where(a>0)

np.where(a==0) # 0의 위치는 어디있는지 알려주는 함수

M1=np.array([100.,
             101.,
             102.,
             103.,
             104.])
M1[[0,2,4]] # indexing을 해서 여러개의 리스트 값을 가져옴

M1[0:3:1] # 0번째부터 3번째 이전까지 1의 차수만큼 가져옴
M1[:] # 모든 리스트를 가져옴
M1[::2] # 앞의 조건 없이 2의 차수만큼 가져옴

M2=np.array([[100., 101., 102],
             [200.,201.,202]])
M2[0][2] # 0번째 차원속의 2번째 리스트의 값을 출력
M2[0,2] # 위와 같음

Y=M2[:,2]
Y.shape
Y

Y=Y[:,np.newaxis]
Y
Y.shape

M2[:,[0,2]]

M3=np.array([
    [
        [100.,101.,102.,103.],
        [104.,105.,106.,107.],
        [108.,109.,110.,111.]],
        [[200.,201.,202.,203.],
         [204.,205.,206.,207.],
         [208.,209.,210.,211]]
             ])

M3[0,:,:]
M3[1,:,:]

x=np.array([10.,20.,30.])
idx=np.where(x==30)
x[idx]

idx=np.where(x==30.)
idx

idx=(x==30)
x[idx]
idx

#where() or nonzero()
x[np.where(x==30)]
np.nonzero(x==30)

#image
IMAGE=np.array([[255,0,255],
                 [255,0,255],
                 [255,0,255]])

idx=np.where(IMAGE==255)

IMAGE[idx]=0
IMAGE
idx


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

## Numpy Linear Algebra

In [40]:
M=np.array([[10,20],[30,40]])
N=np.array([[1,2],[3,4]])

#print(M)
#print(N)
#M*N

M@N # 행렬 연산 '@'
M.dot(N) # 행렬 연산 함수 'dot'

a=np.zeros((3,3)) # 0으로만 구성된 3*3 행렬 생성
b=np.ones((3,3)) # 1로만 구성된 3*3 행렬 생성

c=np.trace(b) # b 행렬의 대각선 방향을 다 더한 값을 출력

M=np.array([[1.,-3.,],
            [2.,4.]])
y=np.array([[1.],[3.]])

M_inv=np.linalg.inv(M) # M 행렬의 inverse(해)를 찾아줌

x=M_inv@y
x

x=np.linalg.solve(M,y) # 위의 방법 inverse의 과정을 한줄로 표현한 코드
print(x)
lin_eig=np.linalg.eig(M)
print(lin_eig)

[[1.3]
 [0.1]]
(array([2.5+1.93649167j, 2.5-1.93649167j]), array([[ 0.77459667+0.j ,  0.77459667-0.j ],
       [-0.38729833-0.5j, -0.38729833+0.5j]]))


## SVD(Singular Value Decomposition)

In [46]:
np.linalg.svd(M)

N=np.zeros((5,5)) # 0으로 채운 5*5 행렬 생성
fill_diag=np.fill_diagonal(N,100) # 대각선 방향으로만 100을 채워 넣음
print(fill_diag)
N

None


array([[100.,   0.,   0.,   0.,   0.],
       [  0., 100.,   0.,   0.,   0.],
       [  0.,   0., 100.,   0.,   0.],
       [  0.,   0.,   0., 100.,   0.],
       [  0.,   0.,   0.,   0., 100.]])

### Numpy를 활용하여 행렬을 변환한 계산

In [77]:
A=np.array([[10,20,30],
           [40,50,60],
           [70,80,90]])

B=np.array(
    [
        [1],
        [2],
        [3]
    ]
)

#B=B.repeat(3,axis=1) # 열 방향으로 각 열의 값을 앞의 숫자(3) 만큼 반복한 행렬 생성
#B
#A*B

# broadcasting
# function uasge example
def f(x,y):
    return x*y
B=np.fromfunction(f,(5,4),dtype=int) # f(x,y) 함수를 생성한 후 각 인덱스별로 곱하는 행렬을 생성 인덱스의 시작은 0부터임.
print(B)

# set
a=np.array([10,20,30,40,50])
b=np.array([30,50])
np.setdiff1d(a,b) # a와b가 교차하지 않는 원소를 추출

x1=np.random.randint(100) # 정수로된 숫자중 0-100 사이의 정수 하나를 추출
x2=np.random.rand(5) # 다섯개의 실수를 추출
print(x1,x2)

[[ 0  0  0  0]
 [ 0  1  2  3]
 [ 0  2  4  6]
 [ 0  3  6  9]
 [ 0  4  8 12]]
31 [0.18962865 0.18381386 0.44735672 0.98136313 0.15819126]
